on:
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest
    env:
      VERSION: ""

    steps:
#get latex tools
    - run: sudo apt -y update
    - run: sudo apt -y install texlive-latex-base texlive-fonts-recommended texlive-latex-extra
    - run: sudo apt -y install texlive-fonts-extra
    - run: sudo apt -y install texlive-lang-cyrillic
#get python and needed libs
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - run: python -m pip install --upgrade pip
    - run: pip install -r scripts/requirements.txt
#get svg tools
    - run: sudo apt -y install librsvg2-bin
