on:
  workflow_dispatch:
    inputs:
      sign:
        type: choice
        description: Significance of changes
        options:
        - major
        - minor
        - patch
      draft:
        description: 'Make unpublished'
        required: true
        type: boolean
        default: false

jobs:
  build-book:
    runs-on: ubuntu-latest
    env:
      VERSION: ""

    steps:
#    - uses: actions/checkout@v3

#genereate new version tag
    - name: "Get next version"
      if: inputs.draft==false
      run: |
        curl --silent -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/keepseasy/Threads-of-Fate/releases/latest |
        grep '"tag_name":' |
        sed -E 's/.*"([^"]+)".*/\1/' >> tmp.txt
        newtag=""
        if [[ "${{ inputs.sign == 'major' }}" = "true" ]]; then
         newtag="VERSION=$((`cut -d. -f1 tmp.txt`+1)).0.0"
        elif [[ "${{ inputs.sign == 'minor' }}" = "true" ]]; then
         newtag="VERSION=`cut -d. -f1 tmp.txt`.$((`cut -d. -f2 tmp.txt`+1)).0"
        elif [[ "${{ inputs.sign == 'patch' }}" = "true" ]]; then
         newtag="VERSION=`cut -d. -f1 tmp.txt`.`cut -d. -f2 tmp.txt`.$((`cut -d. -f3 tmp.txt`+1))"
        else
         exit 1
        fi
        echo $newtag >> $GITHUB_ENV
    - name: "Check generated"
      run: echo "${{ env.VERSION }}"
